### ISSUE TITLE
单机多卡如何设置

### ISSUE THREAD

**Issue by rela0426** [zhoujx4/DuEE#8]
你好~
按照你的步骤，源代码很轻松就跑下来了，比paddle版本结构更清晰，非常感谢~
后来我在这个版本的基础上，加lstm_crf层以后，状况就比较多了~提示内存不足，所以我就考虑改为多卡运行。因为我的服务器有2个GPU，多卡部分代码如下：
```python
model = bert_lstm_crf(args.model_name_or_path, args.id2label,num_classes=args.num_classes,
rnn_hidden_size=args.rnn_hidden_size,rnn_layers=args.rnn_layers)
    model.cuda()
    net = nn.DataParallel(model)
    model=net.module
    # model.to(args.device)
```
但是运行过程中，GPU的利用率情况是下面这样的：
![QQ截图20211115104944](https://user-images.githubusercontent.com/73818025/141714644-ab1f6948-bb53-41b9-9398-e26a250f2233.png)

依旧是1个GPU在跑，而且显存已经快爆了，但是利用率却不高。另外一个GPU一直不动。在你的代码里，有一个参数是do_distri_train，跟它有关系吗？
求帮忙，谢谢~~

**Comment by zhoujx4** [comment]
你好哈~我记得我跑时没有用到多卡，do_distri_train这个参数其实是没有用上的，多卡部分要你自己参考pytorch官方的文档了，不难的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoujx4/DuEE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 上午10:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoujx4/DuEE] 单击多卡如何设置 (Issue #8)





 
你好~
 按照你的步骤，源代码很轻松就跑下来了，比paddle版本结构更清晰，非常感谢~
 后来我在这个版本的基础上，加lstm_crf层以后，状况就比较多了~提示内存不足，所以我就考虑改为多卡运行。因为我的服务器有2个GPU，多卡部分代码如下：
 model = bert_lstm_crf(args.model_name_or_path, args.id2label,num_classes=args.num_classes, rnn_hidden_size=args.rnn_hidden_size,rnn_layers=args.rnn_layers)     model.cuda()     net = nn.DataParallel(model)     model=net.module     # model.to(args.device)
 
但是运行过程中，GPU的利用率情况是下面这样的：
 
 
依旧是1个GPU在跑，而且显存已经快爆了，但是利用率却不高。另外一个GPU一直不动。在你的代码里，有一个参数是do_distri_train，跟它有关系吗？
 求帮忙，谢谢~~
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
